### ISSUE TITLE
Confusion on implementation of 'get_mixture_coef()'

### ISSUE THREAD

**Issue by xueeinstein** [AppliedDataSciencePartners/WorldModels#10]
https://github.com/AppliedDataSciencePartners/WorldModels/blob/36ebabf24783991dfe6f86fa5e25c2bee141db77/rnn/arch.py#L29

This line is from the function `get_mixture_coef()`. I wonder if `pi` should have shape `[-1, rollout_length, GAUSSIAN_MIXTURES, 1]` to match the definition of GMM in MDN. In this way, [SketchRNN's implementation](https://github.com/tensorflow/magenta/blob/204c8282ed83c4dc8f099946e026ad1e86f9402a/magenta/models/sketch_rnn/model.py#L307) is a special case of this one when `Z_DIM=2`.

Am I right? I still cannot draw the final conclusion by myself. Hope to discuss with you.

**Comment by davidADSP** [comment]
The pis for each z dimension need to be independent I believe, hence the inclusion of Z_DIM in the final dimension
