### ISSUE TITLE
rnn_r_loss: -0.9799

### ISSUE THREAD

**Issue by marooncn** [AppliedDataSciencePartners/WorldModels#15]
Hi @davidADSP,
When I train the rnn model,  it's weird that  the rnn_r_loss decrease to negative value. I check the rnn_r_loss defined as:
`result = -K.log(result + 1e-8)`
it should not be a negative value. But it happens.
How does it happen and how can I solve the problem? Thank you.

**Comment by davidADSP** [comment]
That line isn't in this repo - as far as I can see the RNN trains correctly and the loss function is correct.
