### ISSUE TITLE
Replace "master/slave" in 05_train_controller.py with "leader/follower" (or "primary/replica")

### ISSUE THREAD

**Issue by DCtheTall** [AppliedDataSciencePartners/WorldModels#27]
From [PR #2692](https://github.com/django/django/pull/2692) to Django made in 2014:

> The docs and some tests contain references to a master/slave db configuration.
> While this terminology has been used for a long time, those terms may carry racially charged meanings to users.
> This patch replaces all occurrences of master and slave with 'leader' and 'follower'

I'd be happy to make the PR if the owners of this repo are interested!

**Comment by davidADSP** [comment]
Done 👍
